# Generated by Django 4.2.2 on 2023-08-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_be_contacted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="can_data_be_shared",
            field=models.BooleanField(default=False),
        ),
    ]
