# Generated by Django 4.2.2 on 2023-06-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("back-end", "Back-End"),
                    ("front-end", "Front-End"),
                    ("iOS", "iOS"),
                    ("Android", "Android"),
                ],
                max_length=20,
            ),
        ),
    ]
