# Generated by Django 4.2.2 on 2023-07-21 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_comment_uuid_alter_issue_priority_alter_issue_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contributor",
        ),
    ]
